title: Recipes
email: ian.daniel.crosby@gmail.com
description: Collection of recipes with the life stories.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  idcrosby

# Build settings
remote_theme: wowthemesnet/mediumish-theme-jekyll
plugins:
  - jekyll-feed
collections:
  recipes:
    output: true
    permalink: /:name/
    layout: "recipe"
header_pages:
  - index.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
