remote_theme: wowthemesnet/mediumish-theme-jekyll
title: Recipes
description: Collection of recipes without the fluff
collections:
  recipes:
    output: true
    permalink: /:name/
    layout: "recipe"
header_pages:
  - index.md
